CREATE TABLE IF NOT EXISTS users (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 identity_key VARCHAR(191) COLLATE "C" NOT NULL UNIQUE,
 name VARCHAR(191) NOT NULL,
 created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 last_login_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS sessions (
 token_hash CHAR(64) PRIMARY KEY,
 user_id BIGINT NOT NULL,
 expires_at TIMESTAMPTZ NOT NULL,
 FOREIGN KEY (user_id) REFERENCES users(id)
);
CREATE TABLE IF NOT EXISTS oauth_states (
 token_hash CHAR(64) PRIMARY KEY,
 expires_at TIMESTAMPTZ NOT NULL
);
CREATE TABLE IF NOT EXISTS adn_accounts (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 name VARCHAR(191) NOT NULL,
 account_code VARCHAR(191) COLLATE "C" NOT NULL UNIQUE,
 created_by BIGINT NOT NULL,
 created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY (created_by) REFERENCES users(id)
);
CREATE TABLE IF NOT EXISTS uploads (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 user_id BIGINT NOT NULL,
 uploader_name VARCHAR(191) NOT NULL,
 operator_name VARCHAR(191) NOT NULL,
 account_id BIGINT NOT NULL,
 original_name VARCHAR(255) NOT NULL,
 sheet_name VARCHAR(191) NOT NULL,
 sha256 CHAR(64) NOT NULL,
 csv_path VARCHAR(255) NOT NULL,
 columns_json JSONB NOT NULL,
 row_count INT NOT NULL,
 total_amount DECIMAL(30,6) NOT NULL,
 date_from DATE NOT NULL,
 date_to DATE NOT NULL,
 created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY (user_id) REFERENCES users(id),
 FOREIGN KEY (account_id) REFERENCES adn_accounts(id),
 CONSTRAINT uq_upload UNIQUE (user_id,account_id,sha256,sheet_name)
);
CREATE TABLE IF NOT EXISTS settlement_rows (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 upload_id BIGINT NOT NULL,
 source_row INT NOT NULL,
 settlement_date DATE NOT NULL,
 settlement_count DECIMAL(24,6) NOT NULL,
 unit_price DECIMAL(24,6) NOT NULL,
 amount DECIMAL(24,6) NOT NULL,
 extra_fields JSONB NOT NULL,
 source_values JSONB NOT NULL,
 FOREIGN KEY (upload_id) REFERENCES uploads(id),
 CONSTRAINT uq_upload_row UNIQUE (upload_id,source_row)
);

CREATE INDEX IF NOT EXISTS idx_session_expiry ON sessions (expires_at);
CREATE INDEX IF NOT EXISTS idx_session_user ON sessions (user_id);
CREATE INDEX IF NOT EXISTS idx_account_creator ON adn_accounts (created_by);
CREATE INDEX IF NOT EXISTS idx_upload_owner ON uploads (user_id,created_at);
CREATE INDEX IF NOT EXISTS idx_upload_account ON uploads (account_id,created_at);
CREATE INDEX IF NOT EXISTS idx_settlement_date ON settlement_rows (settlement_date);

COMMENT ON COLUMN users.id IS '用户主键，自增 ID';
COMMENT ON COLUMN users.identity_key IS '唯一登录身份：钉钉为 ding:unionId，本地管理员为 local:用户名，区分大小写';
COMMENT ON COLUMN users.name IS '当前用户姓名：钉钉昵称或本地管理员名称，登录时更新';
COMMENT ON COLUMN users.created_at IS '首次登录创建用户的时间，UTC';
COMMENT ON COLUMN users.last_login_at IS '最近一次成功登录时间，UTC';
COMMENT ON TABLE users IS '登录用户表：记录钉钉用户或本地管理员身份';
COMMENT ON COLUMN sessions.token_hash IS '浏览器登录会话令牌的 SHA-256 哈希，64 位十六进制，不保存原始令牌';
COMMENT ON COLUMN sessions.user_id IS '登录用户 ID，关联 users.id，用于确定访问权限';
COMMENT ON COLUMN sessions.expires_at IS '会话到期时间，UTC，登录后有效期为 7 天';
COMMENT ON TABLE sessions IS '登录会话表：保存会话令牌哈希及有效期，退出登录时删除';
COMMENT ON COLUMN oauth_states.token_hash IS 'OAuth state 随机值的 SHA-256 哈希，同时与发起授权的浏览器 Cookie 校验';
COMMENT ON COLUMN oauth_states.expires_at IS '授权状态到期时间，UTC，创建后有效期为 10 分钟';
COMMENT ON TABLE oauth_states IS '钉钉 OAuth 授权状态表：校验授权回调，状态只能使用一次';
COMMENT ON COLUMN adn_accounts.id IS 'ADN 账户主键，自增 ID';
COMMENT ON COLUMN adn_accounts.name IS 'ADN 账户显示名称，由创建人员填写';
COMMENT ON COLUMN adn_accounts.account_code IS '实际 ADN 账号或账户 ID，全平台唯一且区分大小写';
COMMENT ON COLUMN adn_accounts.created_by IS '创建该账户的登录用户 ID，关联 users.id';
COMMENT ON COLUMN adn_accounts.created_at IS '账户创建时间，UTC';
COMMENT ON TABLE adn_accounts IS 'ADN 账户目录表：记录结算文件关联的业务账户，供登录成员选择';
COMMENT ON COLUMN uploads.id IS '上传批次主键，自增 ID';
COMMENT ON COLUMN uploads.user_id IS '实际上传用户 ID，关联 users.id，普通用户的数据访问权限以此字段为准';
COMMENT ON COLUMN uploads.uploader_name IS '上传时的登录用户姓名快照，不随用户后续改名而变化';
COMMENT ON COLUMN uploads.operator_name IS '本次结算的运营负责人姓名，默认登录姓名，可手工修改，不影响访问权限';
COMMENT ON COLUMN uploads.account_id IS '本次结算关联的 ADN 账户 ID，关联 adn_accounts.id';
COMMENT ON COLUMN uploads.original_name IS '上传的原始 Excel 文件名，含扩展名，不含本地目录';
COMMENT ON COLUMN uploads.sheet_name IS '本次导入的 Excel 工作表名称，一次仅导入一个工作表';
COMMENT ON COLUMN uploads.sha256 IS '整个原始 XLSX 文件的 SHA-256 哈希，结合用户、账户和工作表防止重复上传';
COMMENT ON COLUMN uploads.csv_path IS '归档 CSV 的随机文件名，相对于配置 DataDir 下的 csv 目录';
COMMENT ON COLUMN uploads.columns_json IS '原始表头的 JSON 字符串数组，按 Excel 列顺序保存，用于动态展示和 CSV 输出';
COMMENT ON COLUMN uploads.row_count IS '成功入库的有效数据行数，不含表头及空行';
COMMENT ON COLUMN uploads.total_amount IS '本批次所有明细结算金额之和，单位元，精确到 6 位小数';
COMMENT ON COLUMN uploads.date_from IS '本批次明细中最早的结算日期，业务日期，不作时区转换';
COMMENT ON COLUMN uploads.date_to IS '本批次明细中最晚的结算日期，业务日期，不作时区转换';
COMMENT ON COLUMN uploads.created_at IS '上传批次记录创建时间，UTC';
COMMENT ON TABLE uploads IS '结算上传批次表：每条记录对应一次成功导入的 Excel 工作表及其 CSV';
COMMENT ON COLUMN settlement_rows.id IS '结算明细主键，自增 ID';
COMMENT ON COLUMN settlement_rows.upload_id IS '所属上传批次 ID，关联 uploads.id，通过批次关联上传人和 ADN 账户';
COMMENT ON COLUMN settlement_rows.source_row IS '原始 Excel 行号，从 1 开始，表头为第 1 行，保留跳过空行后的实际行号';
COMMENT ON COLUMN settlement_rows.settlement_date IS '标准列「日期」：结算业务日期，统一为 YYYY-MM-DD，不作时区转换';
COMMENT ON COLUMN settlement_rows.settlement_count IS '标准列「结算数」：结算数量，最多 18 位整数及 6 位小数，允许负数调整';
COMMENT ON COLUMN settlement_rows.unit_price IS '标准列「结算单价」：单笔结算价格，单位元，最多 18 位整数及 6 位小数';
COMMENT ON COLUMN settlement_rows.amount IS '标准列「结算金额」：该行结算金额，单位元，最多 18 位整数及 6 位小数，不自动按数量乘单价推算';
COMMENT ON COLUMN settlement_rows.extra_fields IS '四个标准列以外的 JSON 对象，键为原列名、值为原始单元格字符串，如渠道名称、广告位 ID';
COMMENT ON COLUMN settlement_rows.source_values IS '整行原始单元格值的 JSON 字符串数组，与 uploads.columns_json 按下标对应，保留标准化前的值';
COMMENT ON TABLE settlement_rows IS '结算明细表：固定结算字段加动态扩展字段，每条对应 Excel 的一个有效数据行';
