CREATE TABLE IF NOT EXISTS users (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 identity_key VARCHAR(191) COLLATE "C" NOT NULL UNIQUE,
 name VARCHAR(191) NOT NULL,
 created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 last_login_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS sessions (
 token_hash CHAR(64) PRIMARY KEY,
 user_id BIGINT NOT NULL,
 expires_at TIMESTAMPTZ NOT NULL,
 FOREIGN KEY (user_id) REFERENCES users(id)
);
CREATE TABLE IF NOT EXISTS oauth_states (
 token_hash CHAR(64) PRIMARY KEY,
 expires_at TIMESTAMPTZ NOT NULL
);
CREATE TABLE IF NOT EXISTS uploads (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 user_id BIGINT NOT NULL,
 uploader_name VARCHAR(191) NOT NULL,
 operator_name VARCHAR(191) NOT NULL,
 original_name VARCHAR(255) NOT NULL,
 sheet_name VARCHAR(191) NOT NULL,
 sha256 CHAR(64) NOT NULL,
 csv_path VARCHAR(255) NOT NULL,
 columns_json JSONB NOT NULL,
 row_count INT NOT NULL,
 total_amount DECIMAL(30,6) NOT NULL,
 date_from DATE,
 date_to DATE,
 created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY (user_id) REFERENCES users(id)
);
CREATE TABLE IF NOT EXISTS settlement_rows (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 upload_id BIGINT NOT NULL,
 source_row INT NOT NULL,
 agency VARCHAR(255),
 advertiser VARCHAR(255),
 task_name VARCHAR(255),
 settlement_date DATE NOT NULL,
 settlement_count DECIMAL(24,6),
 unit_price DECIMAL(24,6),
 amount DECIMAL(24,6),
 extra_fields JSONB NOT NULL,
 FOREIGN KEY (upload_id) REFERENCES uploads(id)
);

-- Advertiser is the business account, supplied by each imported row.
ALTER TABLE uploads DROP COLUMN IF EXISTS account_id;
DROP TABLE IF EXISTS adn_accounts;

-- Existing imports may lack business key fields. Keep those rows without inventing keys.
ALTER TABLE settlement_rows ADD COLUMN IF NOT EXISTS agency VARCHAR(255);
ALTER TABLE settlement_rows ADD COLUMN IF NOT EXISTS advertiser VARCHAR(255);
ALTER TABLE settlement_rows ADD COLUMN IF NOT EXISTS task_name VARCHAR(255);
ALTER TABLE settlement_rows ALTER COLUMN settlement_count DROP NOT NULL;
ALTER TABLE settlement_rows ALTER COLUMN unit_price DROP NOT NULL;
ALTER TABLE settlement_rows ALTER COLUMN amount DROP NOT NULL;
ALTER TABLE settlement_rows DROP COLUMN IF EXISTS source_values;
ALTER TABLE uploads ALTER COLUMN date_from DROP NOT NULL;
ALTER TABLE uploads ALTER COLUMN date_to DROP NOT NULL;

UPDATE settlement_rows SET agency=btrim(extra_fields->>'代理商') WHERE agency IS NULL AND char_length(btrim(extra_fields->>'代理商')) BETWEEN 1 AND 255;

UPDATE settlement_rows SET advertiser=btrim(extra_fields->>'广告主') WHERE advertiser IS NULL AND char_length(btrim(extra_fields->>'广告主')) BETWEEN 1 AND 255;

UPDATE settlement_rows SET task_name=btrim(extra_fields->>'任务名称') WHERE task_name IS NULL AND char_length(btrim(extra_fields->>'任务名称')) BETWEEN 1 AND 255;

-- Remove the old content-based constraint on existing installations.
-- Historical rows are preserved until an import explicitly matches their business key.
ALTER TABLE uploads DROP CONSTRAINT IF EXISTS uq_upload;
DROP INDEX IF EXISTS idx_upload_replace;
DROP INDEX IF EXISTS idx_upload_scope;
CREATE INDEX IF NOT EXISTS idx_settlement_business ON settlement_rows (settlement_date,agency COLLATE "C",advertiser COLLATE "C");

CREATE INDEX IF NOT EXISTS idx_session_expiry ON sessions (expires_at);
CREATE INDEX IF NOT EXISTS idx_session_user ON sessions (user_id);
CREATE INDEX IF NOT EXISTS idx_upload_owner ON uploads (user_id,created_at);
CREATE INDEX IF NOT EXISTS idx_settlement_date ON settlement_rows (settlement_date);

-- Reuse one file/sheet record per owner and retain immutable import events.
ALTER TABLE uploads ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ;
UPDATE uploads SET updated_at=created_at WHERE updated_at IS NULL;
ALTER TABLE uploads ALTER COLUMN updated_at SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE uploads ALTER COLUMN updated_at SET NOT NULL;
ALTER TABLE settlement_rows DROP CONSTRAINT IF EXISTS uq_upload_row;
CREATE INDEX IF NOT EXISTS idx_settlement_upload ON settlement_rows(upload_id,source_row,id);
CREATE INDEX IF NOT EXISTS idx_upload_updated ON uploads(user_id,updated_at DESC,id DESC);
CREATE TABLE IF NOT EXISTS upload_history (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 upload_id BIGINT NOT NULL REFERENCES uploads(id),
 uploaded_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 uploader_name VARCHAR(191) NOT NULL,
 operator_name VARCHAR(191) NOT NULL,
 inserted_rows INT,
 updated_rows INT,
 source_json JSONB NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_upload_history ON upload_history(upload_id,uploaded_at DESC,id DESC);
INSERT INTO upload_history(upload_id,uploaded_at,uploader_name,operator_name,source_json)
 SELECT u.id,u.created_at,u.uploader_name,u.operator_name,
 jsonb_build_object('original_upload_id',u.id,'csv_path',u.csv_path,'sha256',u.sha256,'columns',u.columns_json)
 FROM uploads u WHERE NOT EXISTS (SELECT 1 FROM upload_history h WHERE h.upload_id=u.id);
-- Consolidate old same-name batches, preserving every remaining detail and event.
CREATE TEMP TABLE upload_merge ON COMMIT DROP AS
 SELECT id,first_value(id) OVER (PARTITION BY user_id,original_name COLLATE "C",sheet_name COLLATE "C" ORDER BY updated_at DESC,id DESC) AS target,
 count(*) OVER (PARTITION BY user_id,original_name COLLATE "C",sheet_name COLLATE "C") AS copies FROM uploads;
UPDATE uploads u SET columns_json=merged.columns FROM (
 SELECT target,jsonb_agg(name ORDER BY first_order) AS columns FROM (
 SELECT target,name,MIN(ord) first_order FROM (
 SELECT m.target,c.name,row_number() OVER (PARTITION BY m.target ORDER BY b.updated_at DESC,b.id DESC,c.n) ord
 FROM upload_merge m JOIN uploads b ON b.id=m.id
 CROSS JOIN LATERAL jsonb_array_elements_text(b.columns_json) WITH ORDINALITY c(name,n) WHERE m.copies>1
 ) ordered GROUP BY target,name) names GROUP BY target
) merged WHERE u.id=merged.target;
UPDATE settlement_rows r SET upload_id=m.target FROM upload_merge m WHERE r.upload_id=m.id AND m.id<>m.target;
UPDATE upload_history h SET upload_id=m.target FROM upload_merge m WHERE h.upload_id=m.id AND m.id<>m.target;
UPDATE uploads u SET created_at=(SELECT MIN(uploaded_at) FROM upload_history WHERE upload_id=u.id),
 row_count=(SELECT COUNT(*) FROM settlement_rows WHERE upload_id=u.id),
 total_amount=(SELECT COALESCE(SUM(amount),0) FROM settlement_rows WHERE upload_id=u.id),
 date_from=(SELECT MIN(settlement_date) FROM settlement_rows WHERE upload_id=u.id),
 date_to=(SELECT MAX(settlement_date) FROM settlement_rows WHERE upload_id=u.id)
 WHERE u.id IN (SELECT target FROM upload_merge WHERE copies>1);
DELETE FROM uploads u USING upload_merge m WHERE u.id=m.id AND m.id<>m.target;
CREATE UNIQUE INDEX IF NOT EXISTS uq_upload_file ON uploads(user_id,original_name COLLATE "C",sheet_name COLLATE "C");
COMMENT ON COLUMN uploads.updated_at IS '最近一次成功上传时间，UTC，用于列表排序';
COMMENT ON TABLE upload_history IS '不可变上传历史，同名文件复用上传记录，每次成功导入保留独立事件和归档信息';
COMMENT ON COLUMN upload_history.id IS '上传历史主键，自增 ID';
COMMENT ON COLUMN upload_history.upload_id IS '所属结算文件记录 ID，关联 uploads.id';
COMMENT ON COLUMN upload_history.uploaded_at IS '本次成功上传时间，UTC';
COMMENT ON COLUMN upload_history.uploader_name IS '本次实际上传用户姓名快照';
COMMENT ON COLUMN upload_history.operator_name IS '本次运营负责人姓名快照';
COMMENT ON COLUMN upload_history.inserted_rows IS '本次新增明细数，历史迁移无法还原时为 NULL';
COMMENT ON COLUMN upload_history.updated_rows IS '本次更新业务键数，历史迁移无法还原时为 NULL';
COMMENT ON COLUMN upload_history.source_json IS '本次不可变归档信息：CSV 相对路径、XLSX 哈希和原始表头，迁移记录另含原批次 ID';

COMMENT ON COLUMN users.id IS '用户主键，自增 ID';
COMMENT ON COLUMN users.identity_key IS '唯一登录身份：钉钉为 ding:unionId，本地管理员为 local:用户名，区分大小写';
COMMENT ON COLUMN users.name IS '当前用户姓名：钉钉昵称或本地管理员名称，登录时更新';
COMMENT ON COLUMN users.created_at IS '首次登录创建用户的时间，UTC';
COMMENT ON COLUMN users.last_login_at IS '最近一次成功登录时间，UTC';
COMMENT ON TABLE users IS '登录用户表：记录钉钉用户或本地管理员身份';
COMMENT ON COLUMN sessions.token_hash IS '浏览器登录会话令牌的 SHA-256 哈希，64 位十六进制，不保存原始令牌';
COMMENT ON COLUMN sessions.user_id IS '登录用户 ID，关联 users.id，用于确定访问权限';
COMMENT ON COLUMN sessions.expires_at IS '会话到期时间，UTC，登录后有效期为 7 天';
COMMENT ON TABLE sessions IS '登录会话表：保存会话令牌哈希及有效期，退出登录时删除';
COMMENT ON COLUMN oauth_states.token_hash IS 'OAuth state 随机值的 SHA-256 哈希，同时与发起授权的浏览器 Cookie 校验';
COMMENT ON COLUMN oauth_states.expires_at IS '授权状态到期时间，UTC，创建后有效期为 10 分钟';
COMMENT ON TABLE oauth_states IS '钉钉 OAuth 授权状态表：校验授权回调，状态只能使用一次';
COMMENT ON COLUMN uploads.id IS '上传批次主键，自增 ID';
COMMENT ON COLUMN uploads.user_id IS '实际上传用户 ID，关联 users.id，普通用户的数据访问权限以此字段为准';
COMMENT ON COLUMN uploads.uploader_name IS '上传时的登录用户姓名快照，不随用户后续改名而变化';
COMMENT ON COLUMN uploads.operator_name IS '本次结算的运营负责人姓名，默认登录姓名，可手工修改，不影响访问权限';
COMMENT ON COLUMN uploads.original_name IS '原始 Excel 文件名，含扩展名不含目录，与用户和工作表共同确定列表记录，不参与明细业务键匹配';
COMMENT ON COLUMN uploads.sheet_name IS '本次导入的 Excel 工作表名称，一次仅导入一个工作表';
COMMENT ON COLUMN uploads.sha256 IS '最近一次上传的完整 XLSX 文件 SHA-256 哈希，仅记录来源，不作为去重依据';
COMMENT ON COLUMN uploads.csv_path IS '本次上传时的不可变归档 CSV 文件名，相对 DataDir/csv，页面下载从当前数据库明细生成';
COMMENT ON COLUMN uploads.columns_json IS '当前明细表头数组，最新上传列优先并保留旧额外列，用于明细展示和 CSV 输出';
COMMENT ON COLUMN uploads.row_count IS '当前归属本文件记录的有效明细数，同名复用或跨文件业务键更新后重算';
COMMENT ON COLUMN uploads.total_amount IS '本批次当前有效明细金额之和，空金额不计入，单位元，精确到 6 位小数';
COMMENT ON COLUMN uploads.date_from IS '本批次当前明细最早业务日期，无有效明细时为 NULL';
COMMENT ON COLUMN uploads.date_to IS '本批次当前明细最晚业务日期，无有效明细时为 NULL';
COMMENT ON COLUMN uploads.created_at IS '首次上传时间，UTC，每次导入由 upload_history 追溯';
COMMENT ON TABLE uploads IS '结算文件记录表：同用户同文件名同工作表复用，统计及下载反映当前有效明细';
COMMENT ON COLUMN settlement_rows.id IS '结算明细主键，自增 ID';
COMMENT ON COLUMN settlement_rows.upload_id IS '最后更新此行的上传批次 ID，关联 uploads.id，并作为登录用户数据隔离依据';
COMMENT ON COLUMN settlement_rows.source_row IS '原始 Excel 行号，从 1 开始，表头为第 1 行，保留跳过空行后的实际行号';
COMMENT ON COLUMN settlement_rows.settlement_date IS '标准列「日期」：结算业务日期，统一为 YYYY-MM-DD，不作时区转换';
COMMENT ON COLUMN settlement_rows.settlement_count IS '标准列「结算数」：结算数量，最多 18 位整数及 6 位小数，允许负数调整，空单元格保存 NULL';
COMMENT ON COLUMN settlement_rows.unit_price IS '标准列「结算单价」：单笔结算价格，单位元，最多 18 位整数及 6 位小数，空单元格保存 NULL';
COMMENT ON COLUMN settlement_rows.amount IS '标准列「结算金额」：该行结算金额，单位元，最多 18 位整数及 6 位小数，不自动按数量乘单价推算，空单元格保存 NULL';
COMMENT ON COLUMN settlement_rows.extra_fields IS '七个标准列以外的 JSON 对象，键为原列名、值为原始单元格字符串，如渠道名称、广告位 ID';
COMMENT ON COLUMN settlement_rows.agency IS '标准列「代理商」，与广告主、日期、任务名称组成业务匹配字段，历史缺失值保留空';
COMMENT ON COLUMN settlement_rows.advertiser IS '标准列「广告主」，即业务账户，新上传不能为空，历史缺失值保留空';
COMMENT ON COLUMN settlement_rows.task_name IS '标准列「任务名称」，新上传不能为空，历史缺失值保留空';
COMMENT ON TABLE settlement_rows IS '结算明细表：固定结算字段加动态扩展字段，每条对应 Excel 的一个有效数据行';
